### ISSUE TITLE
improvements: accessibility

### ISSUE THREAD

**Issue by asbhogal** [ofthewildfire/fem-fylo-landing-page#5]
Accessibility will be addressed, including, but not exclusive to:

1. Background-foreground contrast rations (to meet WCAG 2.1 AAA compliance standards)
2. Associated labels for form elements
3. Aria labels on icon links
4. Aria attributes on footer nav links (to discern from header links)

The possibility for E2E accessibility testing via Playwright may also be considered to highlight any additional improvements.

**Comment by ofthewildfire** [comment]
I can't do the testing, but, I will try and fix the listed issues.

**Comment by asbhogal** [comment]
No problemo - happy to review them afterwards and go through the E2E testing at some point

**Comment by ofthewildfire** [comment]
Do not see the colour issue actually ... but I have tried my hand at the labels/aria stuff.

**Comment by asbhogal** [comment]
Have made the following changes:

1. Amended aria-labels for icon links
2. Changed semantics for form incl. attributes
3. Added email label text which is visually hidden but accessible to screen readers
4. Changed color for Fylo link to meet background-foreground standards (AAA)

Holding off on PR for now - will likely need to merge changes made from https://github.com/ofthewildfire/fem-fylo-landing-page/issues/4 into this and then merge to main, otherwise there is a risk of conflict between branches or some changes might not come across from that one
